### ISSUE TITLE
Serbia and Montenegro cities are in Aland Islands

### ISSUE THREAD

**Issue by hamzehaleess** [khsing/laravel-world#12]
its seem that Serbia and Montenegro (id =159)  cities are linked to Aland Islands (id. = 213)

so I think cities with the country Id 213 should be changed to 159 in WorldCitiesTableSeeder

**Comment by khsing** [comment]
yes, you are right. fix it later

**Comment by khsing** [comment]
after investigating, Serbia and Montenegro had been divided into two countries: Republic of Serbia and Montenegro. So, added a new country Montenegro and related capital with it.
