### ISSUE TITLE
This is Awesome

### ISSUE THREAD

**Issue by antoniputra** [khsing/laravel-world#2]
Hi there..

I just review this package. and already give a shot to try this. and it feels awesome. Thanks so much for this **incredible** package.

With this package then I just continue create the api.

anyway, I was wondering how do you know all of the data?

**Comment by khsing** [comment]
Thanks, I just grab from web and ref from other projects, finally I fixed some data manually.

**Comment by antoniputra** [comment]
as I deep dive into this package.. I just realized that Indonesian Cities is not available yet. its only Province for Indonesian

**Comment by khsing** [comment]
Sure, Indonesian just has cities, no provinces provided.
```php
$id = World::getByCode('id');
$id->has_division; // false
$id->cities->all();
```

**Comment by khsing** [comment]
@antoniputra may be you can check this project https://github.com/rinvex/country

**Comment by antoniputra** [comment]
wew. thanks for the information. (y)
