### ISSUE TITLE
Call to undefined function Khsing\World\starts_with()

### ISSUE THREAD

**Issue by muhammedriyaz** [khsing/laravel-world#23]
I have installed laravel-worl and initiated. Whenever I call any method , for eg: _World::getByCode('cn');_  getting this error _Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined function Khsing\World\starts_with()_ . Please help asap.

**Comment by gregorytoscano** [comment]
I had this exact issue. The files I got from the composer command came with an outdated version of WorldTrait.php, I took a look at that code between the two WorldTrait.php files and the two didn't match. Copy the WorldTrait.php code from Github and overwrite your current code. This solved the issue for me.

**Comment by khsing** [comment]
this function does not exist in new Laravel, pls upgrade to v0.9 version.
