### ISSUE TITLE
Cannot make migration

### ISSUE THREAD

**Issue by GoldeNx3** [khsing/laravel-world#4]
Hello, after write in composer "php artisan world:init" cmd shows me this:

"PDOException::("SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x87\xA8\xF0\x9F...' for column 'emoji' at row 1")"

How to fix it?

**Comment by khsing** [comment]
Duplicate of #3 , using utf8mb4 as default mysql database charset.
