### ISSUE TITLE
Invalid country information

### ISSUE THREAD

**Issue by mokhosh** [khsing/laravel-world#42]
I think some countries have wrong continents. For example these Asian countries are listed as European:
- Armenia
- Azerbaijan

**Comment by khsing** [comment]
@mokhosh I am confused right now, according to several pages, Armenia and Azerbaijan belong Europe, but also belong Asia, my datasource might came from different standard. And I just keep the first result. 

what is your suggestion?

**Comment by mokhosh** [comment]
They are most definitely Asian. Just look them up on the map and see how far they are from Europe.

**Comment by khsing** [comment]
@mokhosh you are right, I am updating

**Comment by khsing** [comment]
@mokhosh already updated. check the latest v8.1
